### ISSUE TITLE
Take configuration from environment variables

### ISSUE THREAD

**Issue by zxjinn** [raph2i/synology_backup_exporter#3]
Hey @raph2i this is a wonderful tool, thank you for writing it. 

I wanted to extend it a little bit, but would like your opinion on _how_ you would like it extended first. I am planning on running this in a container (but not on the synology itself), and would rather configure the script with environment variables instead of the `config.json` file.

There are three basic paths forward that I see:
* If the `config.json` doesn't exist, start reading in the values from an environment variable. This is an all or nothing, either use the config file or use env vars.
* Detect what values are missing from the `config.json` and then reach to an env var to fill that value
* Detect what env vars are missing, and reach to the `config.json` to fill that value

Which of these three do you prefer? or something else perhaps.

The last question is, should the script fail and exit if one of the config values doesn't exist, or should it be filled with some kind of default value (like you have in the `config.json.dist` file)?

**Comment by raph2i** [comment]
Hey @zxjinn ,
thank you for this issue!

I'll would use option 2 (take everything from config.json, and whats missing from environment).
I was already thinking about this since DSM7, to easy monitor multiple instances.

I think the script should fail, or we check if activebackup/vault/hyperbackup is installed and active it as default.

**Comment by zxjinn** [comment]
Hi @raph2i I have addressed this in PR #4, which should auto close this Issue if you accept/merge that PR. Thanks!
